// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/core/_user/v1/user.proto

package userpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserCore with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserCore) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserCore with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserCoreMultiError, or nil
// if none found.
func (m *UserCore) ValidateAll() error {
	return m.validate(true)
}

func (m *UserCore) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQid()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserCoreValidationError{
					field:  "Qid",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserCoreValidationError{
					field:  "Qid",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQid()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserCoreValidationError{
				field:  "Qid",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Md != nil {

		if all {
			switch v := interface{}(m.GetMd()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserCoreValidationError{
						field:  "Md",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserCoreValidationError{
						field:  "Md",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMd()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserCoreValidationError{
					field:  "Md",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Mmd != nil {

		if all {
			switch v := interface{}(m.GetMmd()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserCoreValidationError{
						field:  "Mmd",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserCoreValidationError{
						field:  "Mmd",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMmd()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserCoreValidationError{
					field:  "Mmd",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.BasicAccount != nil {

		if all {
			switch v := interface{}(m.GetBasicAccount()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserCoreValidationError{
						field:  "BasicAccount",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserCoreValidationError{
						field:  "BasicAccount",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBasicAccount()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserCoreValidationError{
					field:  "BasicAccount",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserCoreMultiError(errors)
	}

	return nil
}

// UserCoreMultiError is an error wrapping multiple validation errors returned
// by UserCore.ValidateAll() if the designated constraints aren't met.
type UserCoreMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserCoreMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserCoreMultiError) AllErrors() []error { return m }

// UserCoreValidationError is the validation error returned by
// UserCore.Validate if the designated constraints aren't met.
type UserCoreValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserCoreValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserCoreValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserCoreValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserCoreValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserCoreValidationError) ErrorName() string { return "UserCoreValidationError" }

// Error satisfies the builtin error interface
func (e UserCoreValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserCore.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserCoreValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserCoreValidationError{}

// Validate checks the field values on BasicAccount with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BasicAccount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BasicAccount with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BasicAccountMultiError, or
// nil if none found.
func (m *BasicAccount) ValidateAll() error {
	return m.validate(true)
}

func (m *BasicAccount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUsername()); l < 1 || l > 256 {
		err := BasicAccountValidationError{
			field:  "Username",
			reason: "value length must be between 1 and 256 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BasicAccountMultiError(errors)
	}

	return nil
}

// BasicAccountMultiError is an error wrapping multiple validation errors
// returned by BasicAccount.ValidateAll() if the designated constraints aren't met.
type BasicAccountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BasicAccountMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BasicAccountMultiError) AllErrors() []error { return m }

// BasicAccountValidationError is the validation error returned by
// BasicAccount.Validate if the designated constraints aren't met.
type BasicAccountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BasicAccountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BasicAccountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BasicAccountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BasicAccountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BasicAccountValidationError) ErrorName() string { return "BasicAccountValidationError" }

// Error satisfies the builtin error interface
func (e BasicAccountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBasicAccount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BasicAccountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BasicAccountValidationError{}

// Validate checks the field values on BasicAuth with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BasicAuth) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BasicAuth with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BasicAuthMultiError, or nil
// if none found.
func (m *BasicAuth) ValidateAll() error {
	return m.validate(true)
}

func (m *BasicAuth) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUsername()); l < 1 || l > 256 {
		err := BasicAuthValidationError{
			field:  "Username",
			reason: "value length must be between 1 and 256 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPassword()); l < 16 || l > 72 {
		err := BasicAuthValidationError{
			field:  "Password",
			reason: "value length must be between 16 and 72 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPasshash() != "" {

		if l := utf8.RuneCountInString(m.GetPasshash()); l < 16 || l > 256 {
			err := BasicAuthValidationError{
				field:  "Passhash",
				reason: "value length must be between 16 and 256 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return BasicAuthMultiError(errors)
	}

	return nil
}

// BasicAuthMultiError is an error wrapping multiple validation errors returned
// by BasicAuth.ValidateAll() if the designated constraints aren't met.
type BasicAuthMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BasicAuthMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BasicAuthMultiError) AllErrors() []error { return m }

// BasicAuthValidationError is the validation error returned by
// BasicAuth.Validate if the designated constraints aren't met.
type BasicAuthValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BasicAuthValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BasicAuthValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BasicAuthValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BasicAuthValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BasicAuthValidationError) ErrorName() string { return "BasicAuthValidationError" }

// Error satisfies the builtin error interface
func (e BasicAuthValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBasicAuth.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BasicAuthValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BasicAuthValidationError{}

// Validate checks the field values on JWT with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *JWT) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JWT with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in JWTMultiError, or nil if none found.
func (m *JWT) ValidateAll() error {
	return m.validate(true)
}

func (m *JWT) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Jwt

	if len(errors) > 0 {
		return JWTMultiError(errors)
	}

	return nil
}

// JWTMultiError is an error wrapping multiple validation errors returned by
// JWT.ValidateAll() if the designated constraints aren't met.
type JWTMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JWTMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JWTMultiError) AllErrors() []error { return m }

// JWTValidationError is the validation error returned by JWT.Validate if the
// designated constraints aren't met.
type JWTValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JWTValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JWTValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JWTValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JWTValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JWTValidationError) ErrorName() string { return "JWTValidationError" }

// Error satisfies the builtin error interface
func (e JWTValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJWT.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JWTValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JWTValidationError{}
